name: Station Response Manager Build Windows

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write 

jobs:
  Build-Windows:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
          python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if (Test-Path "requirements_win_build.txt") { pip install -r requirements_win_build.txt }
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Get version from tag
      run: echo "VERSION=${{ github.ref_name }}" | Out-File -FilePath $env:GITHUB_ENV -Append
    - name: Replace version in setup.py
      run: |
        (Get-Content setup.py) -replace '__VERSION__', "$env:VERSION" | Set-Content setup.py
    - name: Build with cx_Freeze
      run: |
        python setup.py build
    - name: Rename build output
      run: |
        Move-Item build\RBF_Download_Helper ("build\Station_Response_Manager_" + $env:VERSION + "_Windows")
    - name: Create distribution archive
      run: |
        Compress-Archive -Path ("build\Station_Response_Manager_" + $env:VERSION + "_Windows") -DestinationPath ("Station_Response_Manager_" + $env:VERSION + "_Windows.zip")
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: |
          Station_Response_Manager_${{ github.ref_name }}_Windows.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
